name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Run CRS
        run: docker run --name crs-host -d -p "5000:80" otymko/crs-apache:8.3.12.1855

      - name: Build with Gradle
        run: ./gradlew check --stacktrace

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: junit_report_11
          path: build/reports/tests/test